easy_admin:
    site_name: 'meetjesus open data'
    design:
        brand_color: '#00ff71'
        assets:
            favicon: '/favicon.png'
    list:
        max_results: 20
    entities:
        Diocese:
            label: 'Diocèse'
            list:
                title: "Liste des diocèses"
                fields: ['name', 'region', 'country']
                sort: ['name', 'ASC']
            form:
                title: "Modifier un diocèse"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Information' }
                    - name
                    - url
                    - { type: 'group', css_class: 'col-sm-6', label: 'Géographie' }
                    - region
                    - country
                    - latitude
                    - longitude
            class: App\Entity\Diocese
        Parish:
            label: 'Paroisse'
            list:
                title: "Liste des paroisses"
                fields: ['name', 'type', 'diocese']
                sort: ['name', 'ASC']
            form:
                title: "Modifier une paroisses"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
                    - { property: 'name', label: 'Nom' }
                    - type
                    - commonName
                    - description
                    - { type: 'group', css_class: 'col-sm-6', label: 'Contact' }
                    - { property: 'responsible', label: 'Responsable' }
                    - { property: 'email', type: 'email', type_options: { trim: true } }
                    - { property: 'url', type: 'url' }
                    - { type: 'section', label: 'Numéro de téléphone', icon: 'phone',
                                            help: 'Le même numéro, seul le format change !', css_class: 'danger' }
                    - { property: 'phoneOriginal', type: 'tel' }
                    - { property: 'phone', type: 'tel' }
                    - { property: 'phoneNational', type: 'tel' }
                    - { property: 'phoneInternational', type: 'tel' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Adresse' }
                    - { property: 'streetAddress', label: 'Adresse' }
                    - { property: 'postalCode', label: 'Code postal' }
                    - { property: 'addressLocality', label: 'Ville' }
                    - { property: 'addresses', label: 'Adresses', type_options: { disabled: true } }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Autre' }
                    - { property: 'picture', type: 'url' }
                    - tags
            class: App\Entity\Parish
        Place:
            label: 'Église'
            list:
                title: "Liste des églises"
                fields: ['name', 'streetAddress', 'postalCode', 'addressLocality', 'parish']
                actions: ['show']
                sort: ['name', 'ASC']
            class: App\Entity\Place
            form:
                fields:
                    - name
                    - { property: 'streetAddress', label: 'Adresse' }
                    - { property: 'postalCode', label: 'Code postal' }
                    - { property: 'addressLocality', label: 'Ville' }
                    - { property: 'addressCountry', type: 'App\Type\CountryType', label: 'Pays' }
                    - latitude
                    - longitude
                    - { property: 'picture', type: 'url' }
            show:
                title: "Église"
                fields:
                    - name
                    - { property: 'streetAddress', label: 'Adresse' }
                    - { property: 'postalCode', label: 'Code postal' }
                    - { property: 'addressLocality', label: 'Ville' }
                    - latitude
                    - longitude
                    - { property: 'picture', type: 'image' }
                    - parish
                    - timetable
        Time:
            label: 'Horaire'
            list:
                title: "Liste des horaires"
                fields: ['id', 'datetime', 'length', 'tags', 'place']
                sort: ['datetime', 'ASC']
            form:
                title: "Modifier un horaire"
                fields:
                    - { property: 'datetime', label: 'Date', type_options: { widget: 'single_text' } }
                    - { property: 'length', label: 'Durée' }
                    - { property: 'isValid', label: 'Valide' }
                    - { property: 'isActive', label: 'Actif' }
                    - tags
                    - { property: 'timeType', label: "Type d'horaire", type: 'choice', type_options: { choices: {'Semaine': 'WEEKMASS', 'Heures': 'HOURSLITURGY', 'Autre': 'OTHERCELEBRATION', 'Fête': 'CELEBRATION', 'Dimanche': 'SUNDAYMASS'} } }
                    - { property: 'celebrationType', label: 'Type de célébration', type: 'choice', type_options: { choices: {'Messe': 'MASS', 'Autre': 'OTHERCELEBRATION', 'Messe de semaine': 'WEEKMASS'} } }
                    - { property: 'recurrenceCategory', label: 'Régularité', type: 'choice', type_options: { choices: {'Régulier': 'REGULAR', 'Choisir une date (?)': 'SELECT_DATE', 'Unique': 'UNIQUE'} } }
            class: App\Entity\Time
        Address:
            label: 'Adresse'
            list:
                title: "Liste des adresses"
                fields:
                    - 'id'
                    - { property: 'streetAddress', label: 'adresse' }
                    - { property: 'postalCode', label: 'Code postal' }
                    - { property: 'addressLocality', label: 'Ville' }
                    - { property: 'origin', label: 'Origine' }
                    - { property: 'parish', label: 'Paroisse' }
            class: App\Entity\Address
