easy_admin:
    site_name: 'meetjesus open data'
    design:
        brand_color: '#00ff71'
        assets:
            favicon: '/favicon.png'
    entities:
        Place:
            class: App\Entity\Place
            form:
                fields:
                    - name
                    - { property: 'addressLocality', label: 'Ville' }
                    - { property: 'postalCode', label: 'Code postal' }
                    - { property: 'streetAddress', label: 'Adresse' }
                    - { property: 'addressCountry', type: 'App\Type\CountryType', label: 'Pays' }
        Time:
            class: App\Entity\Time
        Diocese:
            class: App\Entity\Diocese
        Parish:
            class: App\Entity\Parish
        Address:
            class: App\Entity\Address
