easy_admin:
    site_name: 'meetjesus open data'
    design:
        brand_color: '#00ff71'
        assets:
            favicon: '/favicon.png'
    list:
        max_results: 20
    entities:
        Diocese:
            label: 'Diocèse'
            list:
                title: "Liste des diocèses"
                fields: ['name', 'region', 'country']
                sort: ['name', 'ASC']
            form:
                title: "Modifier un diocèse"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Information' }
                    - name
                    - url
                    - { type: 'group', css_class: 'col-sm-6', label: 'Géographie' }
                    - region
                    - country
                    - latitude
                    - longitude
            class: App\Entity\Diocese
        Parish:
            label: 'Paroisse'
            list:
                title: "Liste des paroisses"
                fields: ['name', 'type', 'diocese']
            form:
                title: "Modifier une paroisses"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
                    - { property: 'name', label: 'Nom' }
                    - type
                    - commonName
                    - description
                    - { property: 'picture', type: 'url' }
                    - tags
                    - { type: 'group', css_class: 'col-sm-6', label: 'Contact' }
                    - { property: 'responsible', label: 'Responsable' }
                    - { property: 'email', type: 'email', type_options: { trim: true } }
                    - { property: 'url', type: 'url' }
                    - { property: 'addresses', label: 'Adresses' }
                    - { type: 'section', label: 'Numéro de téléphone', icon: 'phone',
                                            help: 'Le même numéro, seul le format change !', css_class: 'danger' }
                    - { property: 'phoneOriginal', type: 'tel' }
                    - { property: 'phone', type: 'tel' }
                    - { property: 'phoneNational', type: 'tel' }
                    - { property: 'phoneInternational', type: 'tel' }
            class: App\Entity\Parish
        Place:
            label: 'Église'
            list:
                title: "Liste des églises"
            class: App\Entity\Place
            form:
                fields:
                    - name
                    - { property: 'addressLocality', label: 'Ville' }
                    - { property: 'postalCode', label: 'Code postal' }
                    - { property: 'streetAddress', label: 'Adresse' }
                    - { property: 'addressCountry', type: 'App\Type\CountryType', label: 'Pays' }
        Time:
            label: 'Horaire'
            class: App\Entity\Time
        Address:
            label: 'Adresse'
            list:
                title: "Liste des adresses"
                fields:
                    - 'id'
                    - { property: 'streetAddress', label: 'adresse' }
                    - { property: 'postalCode', label: 'Code postal' }
                    - { property: 'addressLocality', label: 'Ville' }
                    - { property: 'origin', label: 'Origine' }
                    - { property: 'parish', label: 'Paroisse' }
            class: App\Entity\Address
